/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public class Test extends App {
        @Override
        public String getGreeting() {
            return "";
        }
    }
}
